baseURL = "https://script.money"
languageCode = "zh-cn"
relativeURLs = "True"
title = "è„šæœ¬åˆ·é’±"
theme = "github-style"
copyright = "Â© 2020. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"
ignoreErrors = ["error-remote-getjson"]
timeout = 60000
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "è„šæœ¬åˆ·é’±"
  description = "The robot army is already hereâ€”code lets you tell them what to do"
  email = "hello@script.money"
  github = "script-money"
  bilibili = "13448187"
  weibo = "1972885951"
  wechat = "script-money"
  twitter = "scriptdotmoney"
  bitclout = "scriptmoney"
  discord = "https://discord.gg/cryptochasers"
  avatar = "/avatar_box.png"
  url = "https://script.money"
  keywords = "script, automatic, scripts, è„šæœ¬, è‡ªåŠ¨åŒ–, èŠ‚ç‚¹, node, åŒºå—é“¾, blockchain"
  utterances= "script-money/blog-comment"
  lastmod = true
  userStatusEmoji = "ğŸ§±"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]